# Generated by Django 5.2.17 on 2026-08-28 13:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nazwa taga (np. Wege)')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tagi',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nazwa kategorii')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug (URL)')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='recipes.category', verbose_name='Kategoria nadrzędna')),
            ],
            options={
                'verbose_name': 'Kategoria',
                'verbose_name_plural': 'Kategorie',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa przepisu')),
                ('description', models.TextField(verbose_name='Opis / Wstęp')),
                ('prep_time', models.PositiveIntegerField(help_text='Czas w minutach', verbose_name='Czas przygotowania')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='przepisy/glowne/', verbose_name='Zdjęcie główne')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='recipes.category', verbose_name='Kategoria główna')),
                ('tags', models.ManyToManyField(blank=True, related_name='recipes', to='recipes.tag', verbose_name='Tagi')),
            ],
            options={
                'verbose_name': 'Przepis',
                'verbose_name_plural': 'Przepisy',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa produktu (np. Mąka pszenna)')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Ilość')),
                ('unit', models.CharField(max_length=50, verbose_name='Jednostka (np. g, ml, łyżka)')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipe')),
            ],
            options={
                'verbose_name': 'Składnik',
                'verbose_name_plural': 'Składniki',
            },
        ),
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(verbose_name='Numer kroku')),
                ('instruction', models.TextField(verbose_name='Instrukcja')),
                ('image', models.ImageField(blank=True, null=True, upload_to='przepisy/kroki/', verbose_name='Zdjęcie poglądowe')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recipes.recipe')),
            ],
            options={
                'verbose_name': 'Krok przygotowania',
                'verbose_name_plural': 'Kroki przygotowania',
                'ordering': ['step_number'],
            },
        ),
    ]
