# Generated by Django 5.2.17 on 2026-08-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipestep',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='steps', to='recipes.ingredient', verbose_name='Powiązane składniki'),
        ),
    ]
