# Generated by Django 5.2.17 on 2026-08-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipestep_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='diet',
            field=models.CharField(choices=[('dowolna', 'Dowolna'), ('wege', 'Wegetariańska'), ('wegańska', 'Wegańska'), ('bezglutenowa', 'Bezglutenowa'), ('fit', 'Fit / Lekka')], default='dowolna', max_length=50, verbose_name='Dieta'),
        ),
    ]
